# Generated by Django 5.1 on 2025-12-27 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Team name (must be unique)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the team', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Team creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'db_table': 'teams',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='teams_name_12b53a_idx'), models.Index(fields=['created_at'], name='teams_created_d88c0c_idx')],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], db_index=True, default='member', help_text='Member role in the team', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when user joined the team')),
                ('team', models.ForeignKey(help_text='The team this membership belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'db_table': 'team_members',
                'ordering': ['-joined_at'],
            },
        ),
    ]
