# Generated by Django 5.1 on 2025-12-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Project name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the project', max_length=1000)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='planning', help_text='Current project status', max_length=20)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, default='medium', help_text='Project priority level', max_length=20)),
                ('deadline', models.DateTimeField(blank=True, db_index=True, help_text='Project deadline (optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Project creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], db_index=True, default='member', help_text='Member role in the project', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when user joined the project')),
            ],
            options={
                'verbose_name': 'Project Member',
                'verbose_name_plural': 'Project Members',
                'db_table': 'project_members',
                'ordering': ['-joined_at'],
            },
        ),
    ]
