# Generated by Django 5.1 on 2025-12-27 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(help_text='The team this project belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='teams.team', verbose_name='Team'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='project',
            field=models.ForeignKey(help_text='The project this membership belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project', verbose_name='Project'),
        ),
    ]
