# Generated by Django 5.1 on 2025-12-27 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='user',
            field=models.ForeignKey(help_text='The user who is a member of the project', on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['name'], name='projects_name_3fb8fb_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='projects_status_6303d7_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['priority'], name='projects_priorit_bdc554_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['deadline'], name='projects_deadlin_ebe3da_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['team'], name='projects_team_id_f935b2_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_at'], name='projects_created_40bcd1_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['team', 'status'], name='projects_team_id_8db465_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['team', 'priority'], name='projects_team_id_16f6cb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('team', 'name')},
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['project', 'role'], name='project_mem_project_0d0b7d_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['user', 'role'], name='project_mem_user_id_b5a231_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['joined_at'], name='project_mem_joined__070817_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectmember',
            unique_together={('project', 'user')},
        ),
    ]
