# Generated by Django 5.1 on 2025-12-27 14:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('viewed', 'Viewed'), ('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('member_added', 'Member Added'), ('member_removed', 'Member Removed'), ('comment_added', 'Comment Added'), ('attachment_added', 'Attachment Added'), ('login', 'Login'), ('logout', 'Logout')], db_index=True, help_text='Type of action performed', max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='Primary key of the related object (optional)', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional action details in JSON format')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user (optional)', null=True, verbose_name='IP Address')),
                ('user_agent', models.CharField(blank=True, help_text='User agent string (optional)', max_length=500, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the action was performed')),
                ('content_type', models.ForeignKey(blank=True, help_text='Type of the related object (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='contenttypes.contenttype', verbose_name='Content Type')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'db_table': 'activity_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
