# Generated by Django 5.1 on 2025-12-27 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Notification message', max_length=500)),
                ('type', models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed'), ('task_updated', 'Task Updated'), ('task_due_soon', 'Task Due Soon'), ('task_overdue', 'Task Overdue'), ('task_status_changed', 'Task Status Changed'), ('task_priority_changed', 'Task Priority Changed'), ('task_dependency_added', 'Task Dependency Added'), ('task_dependency_completed', 'Task Dependency Completed'), ('project_updated', 'Project Updated'), ('project_member_added', 'Project Member Added'), ('project_member_removed', 'Project Member Removed'), ('project_status_changed', 'Project Status Changed'), ('team_member_added', 'Team Member Added'), ('team_member_removed', 'Team Member Removed'), ('comment_added', 'Comment Added'), ('attachment_added', 'Attachment Added'), ('welcome', 'Welcome'), ('system', 'System Notification')], db_index=True, help_text='Type of notification', max_length=50)),
                ('read', models.BooleanField(db_index=True, default=False, help_text='Whether the notification has been read')),
                ('read_at', models.DateTimeField(blank=True, help_text='Timestamp when notification was read', null=True)),
                ('related_object_id', models.PositiveIntegerField(blank=True, help_text='ID of related object', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional notification metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Notification creation timestamp')),
                ('related_content_type', models.ForeignKey(blank=True, help_text='Content type of related object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
